lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Serbian zipcode have 5 digits: http://en.wikipedia.org/wiki/Postal_codes_in_Serbia
First I thought I might have the country code missed up, but this does not seem the case: http://countrycode.org
=> Serbian zipcode have 5 digits

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
I believe that the brazilian regex was wrong, so I try to fixed it.
Sources for the regex:
- http://www.grcdi.nl/gsb/brazil.html#H653B4E6D1258E62ABD4015F3B8AEECAE0D18981B03FBrazilA20A2DA20A5BA5BPostalA20codeA20regularA20expressionA5DA5D00700A00D01001301C02302D03A03D
- http://networking.mydesigntool.com/viewtopic.php?tid=419&id=31
- https://helpdesk.coresystems.ch/hc/en-us/articles/201972481-BUP-Validate-Brazilian-ZipCode-CEP-correct-format
- http://www.regexlib.com/REDetails.aspx?regexp_id=767
=> Fixed brazilian zipcode regex

lib/validates_zipcode/cldr_regex_collection.rb
CLDR specifies the following regex for SE:
`<postCodeRegex territoryId="SE" >\d{3}[ ]?\d{2}</postCodeRegex>`
The pull request fixes the regex making the space optional.
=> Fix regex for SE

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Recently, Korea updated their zipcode convention to a 5-digit numeric convention. See [this](http://www.fedex.com/tc/koreapostalcode/index.html) or [Wikipedia](https://en.wikipedia.org/wiki/List_of_postal_codes_in_South_Korea).
I made the regex change such that it also applies to the old one. Do you suggest I just go with the new convention altogether?
=> update new korea zipcode regex

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Fix issue #18 
Accept both LT-NNNN (until 2005) and LT-NNNNN (post 2005) formats.
=> Fix LT zipcode format

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Allow 7 digits zipcode to be compatible with post 2013 format, and keep 5 digits legacy format.
Reference: https://en.wikipedia.org/wiki/Postal_codes_in_Israel
=> Fix Israel rules to be compliant with post 2013 format

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Hi, 
The format usually used is "L-XXXX". I have updated the regexp and added the test.
Can you merge this ?
Thank you.
See here : https://www.post.lu/en/grandes-entreprises/solutions-postales/rechercher-un-code-postal
=> LU (Luxembourg) Postcode incorrect

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
We use this gem and were contacted by an user complaining that they can't register because Panama doesn't have zip codes but yet one is required. A quick Google search showed that Panama indeed doesn't seem to have zip codes. This change removes the regex for Panama allowing any zip code.
=> Allow any zipcode for Panama as it doesn't have zipcodes

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Taiwan zipcode can have 2 more optional digits according to https://en.wikipedia.org/wiki/Postal_codes_in_Taiwan
=> Five digits taiwan

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
According to [Wikipedia](https://en.wikipedia.org/wiki/Postal_codes_in_Nicaragua), postal codes in Nicaragua are 5 digit numeric. This PR changes it's regex and adds specs
=> Make Nicaragua (NI) accept 5-digits zipcodes

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Fix for issue #39 
Accept LT-NNNN/LT-NNNNN and NNNN/NNNNN formats.
=> modify lithuania regex to make country_code prefix optional

CHANGELOG.md, README.md, lib/validates_zipcode.rb, lib/validates_zipcode/formatter.rb, lib/validates_zipcode/invalid_zipcode_error.rb, lib/validates_zipcode/zipcode.rb, spec/format_zipcode_spec.rb, spec/validates_zipcode_spec.rb
Start to add support for canonical formatting of country specific zipcodes.
See #43 for the general ideas.
=> add zipcode formatting feature

README.md
**Description**
After version `0.2.4`, a [`:message` option can be passed into the validation declaration](https://github.com/dgilperez/validates_zipcode/pull/46), to set a custom error message on a per-model basis.
This PR documents that change in the `README`. This closes #47.
=> Document the `:message` option

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
See: [https://nl.wikipedia.org/wiki/Postcodes_in_Nederland](https://nl.wikipedia.org/wiki/Postcodes_in_Nederland) the English translation of this page unfortunately did not add this information.
=> Dutch zipcodes never start with a ‘0’ or contain the letter combinations 'SS', 'SD' and 'SA’.

lib/validates_zipcode/cldr_regex_collection.rb, spec/validates_zipcode_spec.rb
Fix error with Netherlands zip code generation, removed lookahead from regexp
=> Make Netherlands regexp compatible with random_example method

lib/validates_zipcode/formatter.rb, lib/validates_zipcode/validator.rb, lib/validates_zipcode/zipcode.rb
Following our discussion on Issue #56 I'm proposing the following changes:
* Add a format option. This option is a boolean. If it's set to `true`, the postcode will be formatted before being validated. By default it's false, which is the current behaviour (= validate what the user entered without formatting it).
* Modify `Zipcode#format` so that the zipcode validation happens on the formatted zipcode instead.
* Modify the German postcode formatting to not substitute 0 to all missing digits. Instead, it's only adding one 0 when the digit count is less than 5 to allow translation of older East Germany postcodes. This avoids the issue explained [here](https://github.com/dgilperez/validates_zipcode/issues/56#issuecomment-847654208).
This means that now …
=> Add a format option that allows formatting postcodes before checking for validity

lib/validates_zipcode/formatter.rb
Puerto Rico uses the same formatting as the US does for postal codes. 
https://en.wikipedia.org/wiki/Postal_codes_in_Puerto_Rico
This change adds formatter support for PR.
=> Puerto Rico uses the same formatting as the US

lib/validates_zipcode/cldr_regex_collection.rb, spec/spec_helper.rb
Honduras appears to have transitions to a 5-digit numeric postal code.
https://en.youbianku.com/honduras
(See the Note under the Coding Method and the examples in List of Postcodes)
This change add support for the 5-digit numeric postal code. I wasn't sure if support for the old codes should be removed so I left it.
=> Honduras has transitioned to 5-digit numeric postal codes

lib/validates_zipcode/formatter.rb, spec/format_zipcode_spec.rb
👋 
Adjusts `ValidatesZipcode::Formatter::ZIPCODES_TRANSFORMATIONS::MT` to match `ValidatesZipcode::CldrRegexpCollection::ZIPCODES_REGEX::MT`.
Currently the formatter changes the format from (e.g.) `GZR1020` to `GZR1 020`, but the regexp validates that the ZIP is in the format `GZR 1020`, so it will always fail for Maltese addresses.
🙏
=> Maltese ZIP formatting

lib/validates_zipcode/cldr_regex_collection.rb, spec/spec_helper.rb
Add NNNN format to AR regexp
https://en.wikipedia.org/wiki/List_of_postal_codes
> Previously NNNN which is the minimum requirement as of 2006, but ANNNNAAA is not mandatory.
=> Allow NNNN zipcode for Argentina
